version: '3.8'

services:
  auth:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - test-net

networks:
  test-net:
    driver: bridge
